version: 0.1

phases:
  install:
    commands:
      - echo Entering install phase...
      - echo Nothing to do now
  build:
    commands:
      - echo Build started on `date`
      - bash ./gradlew clean build -x test -Dquarkus.package.type=native --info
artifacts:
  type: zip
  files:
    - 'build/libs/*.jar'